[package]
name = "str_assert"
version = "0.1.0"
authors = ["Dustin Knopoff <rust@knopoff.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dissimilar = "1.0.2"
